// <auto-generated />
namespace WebUoFASM1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Addnewfortrainee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addnewfortrainee));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280254509_Addnewfortrainee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
