// <auto-generated />
namespace WebUoFASM1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class lanthuen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lanthuen));
        
        string IMigrationMetadata.Id
        {
            get { return "202008281358068_lanthuen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
